config/routes.rb
Rails.application.routes.draw do
  root 'app_names#index'
  resources :app_names
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_name.rb
class AppName < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/app_names_controller.rb
class AppNamesController < ApplicationController
  before_action :set_app_name, only: [:show, :edit, :update, :destroy]

  # GET /app_names
  # GET /app_names.json
  def index
    @app_names = AppName.all
  end

  # GET /app_names/1
  # GET /app_names/1.json
  def show
  end

  # GET /app_names/new
  def new
    @app_name = AppName.new
  end

  # GET /app_names/1/edit
  def edit
  end

  # POST /app_names
  # POST /app_names.json
  def create
    @app_name = AppName.new(app_name_params)

    respond_to do |format|
      if @app_name.save
        format.html { redirect_to @app_name, notice: 'App name was successfully created.' }
        format.json { render :show, status: :created, location: @app_name }
      else
        format.html { render :new }
        format.json { render json: @app_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_names/1
  # PATCH/PUT /app_names/1.json
  def update
    respond_to do |format|
      if @app_name.update(app_name_params)
        format.html { redirect_to @app_name, notice: 'App name was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_name }
      else
        format.html { render :edit }
        format.json { render json: @app_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_names/1
  # DELETE /app_names/1.json
  def destroy
    @app_name.destroy
    respond_to do |format|
      format.html { redirect_to app_names_url, notice: 'App name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_name
      @app_name = AppName.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def app_name_params
      params.require(:app_name).permit(:title, :message)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/app_names_helper.rb
module AppNamesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app_names/_form.html.erb
<%= form_for(app_name) do |f| %>
  <% if app_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app_name.errors.count, "error") %> prohibited this app_name from being saved:</h2>

      <ul>
      <% app_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/app_names/edit.html.erb
<h1>Editing App Name</h1>

<%= render 'form', app_name: @app_name %>

<%= link_to 'Show', @app_name %> |
<%= link_to 'Back', app_names_path %>

app/views/app_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>App Names</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_names.each do |app_name| %>
      <tr>
        <td><%= app_name.title %></td>
        <td><%= app_name.message %></td>
        <td><%= link_to 'Show', app_name %></td>
        <td><%= link_to 'Edit', edit_app_name_path(app_name) %></td>
        <td><%= link_to 'Destroy', app_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App Name', new_app_name_path %>

app/views/app_names/new.html.erb
<h1>New App Name</h1>

<%= render 'form', app_name: @app_name %>

<%= link_to 'Back', app_names_path %>

app/views/app_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @app_name.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @app_name.message %>
</p>

<%= link_to 'Edit', edit_app_name_path(@app_name) %> |
<%= link_to 'Back', app_names_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApri</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>